services:
  backend:
    build: backend
    networks:
      - pep
    ports:
      - "3000:3000"
    volumes:
      - pep-db:/data/db:Z
  frontend:
    build: frontend
    networks:
      - pep
    ports:
      - "8080:8080"

volumes:
  pep-db:
    external: true

networks:
  pep: