# For connection urls to the following instances, see
# https://github.com/prisma/prisma/blob/main/TESTING.md#environment-variables
services:
  backend:
    build: backend
    networks:
      - pep
      - pep-sql
    ports:
      - "5435:5432"
    volumes:
      - pep-db:/data/db:Z
    depends_on:
      - database
  database:
    image: docker.io/library/postgres:12.13-alpine
    networks:
      - pep-sql
    volumes:
      - database-storage:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=${DATABASE_USER:-pep}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-admin}
  frontend:
    build: frontend
    networks:
      - pep
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  pep-db:
    external: true
  database-storage:
networks:
  pep:
  pep-sql: