services:
  backend:
    build: backend
    networks:
      - pep
    ports:
      - "3000:3000" # Kemal Default
    volumes:
      - pep-db:/data/db:Z
  frontend:
    build: frontend
    networks:
      - pep
    ports:
      - "5173:5173" # Vite Default

volumes:
  pep-db:
    external: true

networks:
  pep: